version: 2

rn_defaults: &rn_defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:10.9

jobs:
  install-dependencies:
    <<: *rn_defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project 
      - restore_cache:
          keys:
          - v1-0-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          #- v1-0-dependencies-

      # install rustup
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: echo 'export PATH=$HOME/.cargo/bin/:$PATH' >> $BASH_ENV
      # use nightly version. 
      - run: rustup install nightly-2018-06-05
      - run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
      - run: cargo install cargo-lipo

      - run:
          name: Match bitrise's yarn version
          command: sudo npm install -g yarn@${BITRISE_YARN_VER}

      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: v1-0-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - yarn.lock


      - persist_to_workspace:
          root: .
          paths: .

  flow:
    <<: *rn_defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Match bitrise's yarn version
          command: sudo npm install -g yarn@${BITRISE_YARN_VER}
      - run: yarn flow

  test:
    <<: *rn_defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Match bitrise's yarn version
          command: sudo npm install -g yarn@${BITRISE_YARN_VER}
      - run: yarn test

  lint:
    <<: *rn_defaults
    steps:
      - attach_workspace:
         at: ~/project

      - run:
          name: Match bitrise's yarn version
          command: sudo npm install -g yarn@${BITRISE_YARN_VER}
      # Because npm link will write in this path
      - run: sudo chown -R "$(whoami):$(whoami)" /usr/local/lib/node_modules
      - run: npm link rust-cardano-crypto
      - run: yarn lint

  android:
    working_directory: ~/project/android
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Android NDK
          command: source ./get_android_ndk.sh
      # install rustup
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: echo 'export PATH=$HOME/.cargo/bin/:$PATH' >> $BASH_ENV
      # use nightly version. 
      - run: rustup install nightly-2018-06-05
      - run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
      - run: cargo install cargo-lipo
      - run: export
      - run: cargo
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Android build
          command: ./gradlew assembleRelease

workflows:
  version: 2
  main:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - flow:
          requires:
            - install-dependencies
      - test:
          requires:
            - install-dependencies
#      - android:
#          requires: 
#            - install-dependencies
#            - lint
#            - flow
